name: Pull Request

on:
  workflow_run:
    workflows: ["Lint and tests"]
    types: [completed]
  pull_request:
    branches:
      - "main"
      - "bug-fix-*"
      - "feature-*"

jobs:
  docker-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Write app version
        run: printf "$GITHUB_SHA" > .application-version
      - name: Set Image Tag
        id: set-tag
        run: |
          CLEAN_TAG=$(echo "${{ github.event.pull_request.head.ref }}"  | tr / -)
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
      - name: Build
        run: >
          docker build -t onsdigital/sds:$TAG .
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [$TAG]"
          docker push onsdigital/sds:$TAG