name: Pull Request

on:
  pull_request:
    branches:
      - "main"
      - "SDSS-196-Push-image-to-docker-hub-Github-workflow-build-on-defined-branch-names"
      - "bug-fix-*"
      - "feature-*"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Include lint and test job
      - uses: ./.github/workflows/lint_and_tests.yml

  docker-push:
    needs: lint-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Write app version
        run: printf "$GITHUB_SHA" > .application-version
      - name: Set Image Tag
        id: set-tag
        run: |
          CLEAN_TAG=$(echo "${{ github.event.pull_request.head.ref  }}"  | tr / -)
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
      - name: Build
        run: >
          docker build -t onsdigital/sds:$TAG .
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing with tag [$TAG]"
          docker push onsdigital/sds:$TAG
